
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
      - "5000:5000"
      - "3000:3000"
      - "3002:3002"
      - "3003:3003"
      - "5001:5001"
      - "9000:9000"
      - "8010:8010"
    networks:
      - app-network

  pybackend:
    build: ./pybackend
    ports:
      - "8001:8001"
    networks:
      - app-network

  ml:
    build: ./ML
    ports:
      - "8000:8000"
    networks:
      - app-network

  labr:
    build: ./LAbr
    ports:
      - "8002:8002"  # Fixed port mismatch
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - pybackend
      - ml
      - labr
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
